on:   # yamllint disable-line rule:truthy
  pull_request:

name: Check semver breaks

jobs:
  Prepare:
    runs-on: ubuntu-latest
    outputs:
      stable_version: ${{ steps.read_toolchain.outputs.stable_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Read stable version"
        id: read_toolchain
        run: echo "stable_version=$(cat ./.github/workflows/stable-version)" >> $GITHUB_OUTPUT

  PR:
    name: PR Semver - stable toolchain
    needs: Prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need full history for cargo semver-checks
      - name: "Install Rustup"
        uses: dtolnay/rust-toolchain@stable
      - name: "Select stable-version"
        run: |
          rustup default $(cat ./.github/workflows/stable-version)
      - name: "Install cargo-binstall"
        uses: cargo-bins/cargo-binstall@main
      - name: "Binstall cargo-semver-checks"
        run: cargo binstall cargo-semver-checks@0.32.0 --no-confirm
      - name: "Run semver checker script"
        run: ./contrib/check-semver-pr.sh
      - name: "Save PR Number"
        if: ${{ hashFiles('semver-break') != '' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr-semver-break
          echo $PR_NUMBER > ./pr-semver-break/semver-break-NR
      - name: "Upload PR Number"
        uses: actions/upload-artifact@v4
        if: ${{ hashFiles('semver-break') != '' }}
        with:
          name: pr-semver-break
          path: pr-semver-break/

  Feature:
    name: Non additive cargo features - stable toolchain
    needs: Prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Install Rustup"
        uses: dtolnay/rust-toolchain@stable
      - name: "Select stable-version"
        run: |
          rustup default $(cat ./.github/workflows/stable-version)
      - name: "Install cargo-binstall"
        uses: cargo-bins/cargo-binstall@main
      - name: "Binstall cargo-semver-checks"
        run: cargo binstall cargo-semver-checks@0.32.0 --no-confirm
      - name: "Run semver checker script"
        run: ./contrib/check-semver-feature.sh
      - name: "Save PR Number"
        if: ${{ hashFiles('non-additive-cargo') != '' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr-non-additive-cargo
          echo $PR_NUMBER > ./pr-non-additive-cargo/non-additive-cargo-NR
      - name: "Upload PR Number"
        uses: actions/upload-artifact@v4
        if: ${{ hashFiles('non-additive-cargo') != '' }}
        with:
          name: pr-non-additive-cargo
          path: pr-non-additive-cargo/
